### PR TITLE
Add replicated codelists to projects

### PR DESCRIPTION
**Pull request by andylolz**
I don’t know what the text should say here… How’s does this sound, @markbrough @matmaxgeds?

### CODE REVIEW

**Comment by andylolz** [comment]
Ace – though that could be quite soon! Mark has an open PR to add his exchange rates API: codeforIATI/codelists#21

**Comment by matmaxgeds** [comment]
Having xrates would be cool.......but are they really a codelist? My gut instinct is that this is a separate codeforiati service e.g. there is nothing in IATI where you would specify the exchange rate vocab (although maybe there should be, that way would not have to give the rate, but could give the xrate vocab and the date) but even then, it is not a codelist, unless you say that xrate=hf494g vocab=marks-xrates and on that codelist, hf494g is a lookup to the exchange rate for EUR to JPY on 4th Sept 2015, from the source OECD....

**Comment by markbrough** [comment]
Hey @matmaxgeds -- [exchange rates codelist](https://codelists.codeforiati.org/ExchangeRates/) is now up! It looks a bit different from the other ones. I think we are def keen on having codelists outside the existing set -- basically whatever is useful reference material. That should also at least include `org-id-finder`, I think. Though we might want to consider reorganising this content more in future if we decide there's a more natural home for it.

I think we will also want to expand on existing codelists -- for example, it would be helpful to have a mapping of the `Country` codelist to the `Currency` codelist, and also to the DAC `Region` codelist.

**Comment by matmaxgeds** [comment]
@markbrough very cool that it is in there, as totally agreed that putting as much useful reference material in as possible is good, but I think that what would help is when we get a chance, doing a minor re-factor of the (brand new and cool) codelists minisite e.g. with some way to separate out actual codelists, from all the other bits of info we think are useful i.e. perhaps so that there are categories e.g. 'codelists from the IATI standard' (incl all replicated, non-replicated, core etc) and 'additional codelists/reference material' i.e. data/codelists that are not referenced in IATI data but we think would be useful to process/understand/use IATI data e.g. the exchange rates. Then again, I think that the interest rates are important enough to deserve their own mini-page i.e. exchangerates.codeforiati.org.......but maybe the point of the microsite is to make it easier i.e. not to have to keep setting up subdomains? But basically, I think that both codelists and other material are both essential to have, but it really confused me to have other material on a microsite that was specifically called 'codelists'.codeforiati.org.....and if I was scrolling up and down the list on the right hand site of the codelists microsite, there was no way of knowing which one was a codelist, and which not.

**Comment by andylolz** [comment]
+1, agree with all of the above, I think!

> separate out actual codelists, from all the other bits of info we think are useful i.e. perhaps so that there are categories e.g. 'codelists from the IATI standard' (incl all replicated, non-replicated, core etc) and 'additional codelists/reference material' i.e. data/codelists that are not referenced in IATI data but we think would be useful to process/understand/use IATI data e.g. the exchange rates.

^^ Absolutely. This sounds good to me.

I was also a bit sceptical about putting external APIs onto this site. But I think I’m warming to the idea. I do agree, though, that we should separate them out in some way, so it’s clear that they’re distinct.

> I think that the interest rates are important enough to deserve their own mini-page i.e. exchangerates.codeforiati.org

Totally agree, I think this would also be cool. There’s a ticket on the ideas board here:
https://github.com/codeforIATI/iati-ideas/issues/13

**Comment by markbrough** [comment]
How about something like nesting exchange rates (and a brief page explaining org id finder) under a menu item like "extras" or "community"?

**Comment by matmaxgeds** [comment]
nesting defo a good step forward from my side - just not quite getting it about the benefit of having exchange rates and org-ids as a subset of the codelists microsite. Pro's are that people browsing codelists could see other things that interest them, that the microsite makes it easy to put up pages about these things, but from my side Cons = we have a homepage to put this stuff on, and it confuses me RE the codelists site (which I think is ace, and looking forward to adding a lot of other codelists there)

**Comment by markbrough** [comment]
Makes sense, I agree in the medium term it will probably make sense to move things around more, especially when we have more stuff. But I think it is helpful to bring them together for now because I think they are not very easily discoverable otherwise.

**Pull request merged**
