### PR TITLE
Add DIterator

### PR DESCRIPTION
**Pull request by davidmegginson**
Adding an entry for my Python3 DIterator library at https://github.com/davidmegginson/diterator

### CODE REVIEW

**Comment by markbrough** [comment]
This is super nice, David! Definitely very happy for this to be included!

**Comment by andylolz** [comment]
I just gave it a spin – this is great!

**Comment by davidmegginson** [comment]
Thanks!

**Comment by davidmegginson** [comment]
I noticed my description is too long and messes up the page layout. Would you like me to trim it down?

**Comment by andylolz** [comment]
Ahhh… In general, I think this site is probably due a bit of love. There are quite a lot of projects here now (which is great!)

In the meantime, though, if you don’t mind trimming it down a bit, that would be great.

**Pull request merged**
