### PR TITLE
Add dQuery to projects #64

### PR DESCRIPTION
**Pull request by notshi**
Hope this looks ok. Thank you!

### CODE REVIEW

**Comment by andylolz** [comment]
Hello, sorry! I’ve been moving [to a] house. I’ll take a look now!

**Comment by notshi** [comment]
ahh! no worries - please, take your time and hope the move is not stressing you out (too much) :}

**Review by andylolz — APPROVED** [review]
Great – this looks good to me

**Comment by notshi** [comment]
thank you!!

**Pull request merged**
