### PR TITLE
Add list-filter-toggle-buttons

### PR DESCRIPTION
**Pull request by matmaxgeds**
Add some buttons to filter the list of tools

### CODE REVIEW

**Comment by andylolz** [comment]
Sorry for the delay! I’ve been on holiday.

I’ve just taken a look, and I have some thoughts.

 * you can use [`preventDefault`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) to stop the page reloading when the filters are clicked.
 * I think it might be cool to group the three different filter groups with headings. 
 * I also think I’d find toggle off/on buttons more intuitive. That might mean it’s possible to drop the "both" buttons
 * the button in the top-right says "tools", but there’s a filter that also says "tools". I guess as a temporary fix, the button in the top-right could just disappear, until we have the blog?
 * I’m not totally sure I’m sold on the specific filters, although I think Steven and Mark might be more useful on this front. In particular, I suspect many publishers would still self-define as "users" so I don’t know if that distinction works.

**Review by andylolz — CHANGES_REQUESTED** [review]
Sorry for the delay! I’ve been on holiday.

I’ve just taken a look, and I have some thoughts.

 * you can use [`preventDefault`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) to stop the page reloading when the filters are clicked.
 * I think it might be cool to group the three different filter groups with headings. 
 * I also think I’d find toggle off/on buttons more intuitive. That might mean it’s possible to drop the "both" buttons
 * the button in the top-right says "tools", but there’s a filter that also says "tools". I guess as a temporary fix, the button in the top-right could just disappear, until we have the blog?
 * I’m not totally sure I’m sold on the specific filters, although I think Steven and Mark might be more useful on this front. In particular, I suspect many publishers would still self-define as "users" so I don’t know if that distinction works.

**Comment by matmaxgeds** [comment]
Thanks @andylolz - will get onto it - and this should function as a rolling preview of my fork - for now I will try to put all the different button options there to get opinions: https://htmlpreview.github.io/?https://github.com/matmaxgeds/codeforiati.github.io/blob/master/index.html

**Comment by andylolz** [comment]
I did some refactoring on master, so I’ve just brought this branch back up-to-date.

**Pull request closed without merging**
