### PR TITLE
Add d-preview as a project

### PR DESCRIPTION
**Pull request by notshi**
Hope it's ok to have a dash in the file name. Happy to change otherwise!

### CODE REVIEW

**Comment by andylolz** [comment]
:tada: :tada: :tada:

**Comment by notshi** [comment]
Forgot to link https://github.com/codeforIATI/codeforiati.github.io/issues/50

**Comment by andylolz** [comment]
> Hope it's ok to have a dash in the file name

No idea actually! Let me check locally…

**Comment by andylolz** [comment]
Looks good!

**Comment by andylolz** [comment]
Thanks for adding! 🙌

**Pull request merged**
